import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./styles/index.css";
import Provider from "./store/Provider";
import SideBar from "../app/components/SideBar"; // Adjust the path as necessary
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <div className="flex">
            <Header />
            <SideBar />
            <main className="flex-1">{children}</main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
